export const CATEGORIES_GET_START = 'CATEGORIES_GET_START';
export const CATEGORIES_GET_ERROR = 'CATEGORIES_GET_ERROR';
export const CATEGORIES_GET_SUCCESS = 'CATEGORIES_GET_SUCCES';

export const CATEGORIES_GET_ALL_START = 'CATEGORIES_GET_ALL_START';
export const CATEGORIES_GET_ALL_ERROR = 'CATEGORIES_GET_ALL_ERROR';
export const CATEGORIES_GET_ALL_SUCCESS = 'CATEGORIES_GET_ALL_SUCCESS';

export const CATEGORY_SAVE_START = 'CATEGORY_SAVE_START';
export const CATEGORY_SAVE_ERROR = 'CATEGORY_SAVE_ERROR';
export const CATEGORY_SAVE_SUCCESS = 'CATEGORY_SAVE_SUCCESS';
